# -*- coding: utf-8 -*-
"""Building 3MF geometry from scratch.

Everything here is generated by this file, from numbers in this file. Nothing
is copied from another project, which is why the shrinkage plate can ship in
the repository while the towers cannot - see docs/templates.md.
"""
import datetime
import json
import os
import zipfile


NS_CORE = "http://schemas.microsoft.com/3dmanufacturing/core/2015/02"
NS_CT = "http://schemas.openxmlformats.org/package/2006/content-types"
NS_REL = "http://schemas.openxmlformats.org/package/2006/relationships"

CONTENT_TYPES_MODEL = """<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="{}">
 <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
 <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
</Types>
""".format(NS_CT)

CONTENT_TYPES_PROJECT = """<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="{}">
 <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
 <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
 <Default Extension="png" ContentType="image/png"/>
 <Default Extension="gcode" ContentType="text/x.gcode"/>
 <Default Extension="config" ContentType="application/xml"/>
 <Default Extension="json" ContentType="application/json"/>
 <Default Extension="xml" ContentType="application/xml"/>
</Types>
""".format(NS_CT)

RELS = """<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="{}">
 <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
""".format(NS_REL)

SLICE_INFO = """<?xml version="1.0" encoding="UTF-8"?>
<config>
  <header>
    <header_item key="OrcaSlicer-Version" value="2.4.2"/>
  </header>
</config>
"""


def box(width, depth, height):
    """A rectangular block from the origin: vertices and triangles.

    Triangle winding is counter-clockwise seen from outside, so the normals
    point outward. A slicer given inverted normals either complains or quietly
    prints the part inside out, so this order is worked out rather than
    guessed at.
    """
    vertices = [
        (0, 0, 0), (width, 0, 0), (width, depth, 0), (0, depth, 0),
        (0, 0, height), (width, 0, height), (width, depth, height), (0, depth, height),
    ]
    triangles = [
        (0, 2, 1), (0, 3, 2),   # bottom, normal -Z
        (4, 5, 6), (4, 6, 7),   # top,    normal +Z
        (0, 1, 5), (0, 5, 4),   # front,  normal -Y
        (1, 2, 6), (1, 6, 5),   # right,  normal +X
        (2, 3, 7), (2, 7, 6),   # back,   normal +Y
        (3, 0, 4), (3, 4, 7),   # left,   normal -X
    ]
    return vertices, triangles


def shrinkage_parts():
    """The bar used to measure shrinkage.

    Printed with ordinary settings, solid: measuring the length of a rigid part
    is more accurate than measuring a thin-walled one that warps as it cools.
    The 100 mm baseline is deliberate - over 30 mm the shrinkage disappears
    into the caliper's tolerance.
    """
    width, depth, height = 100.0, 10.0, 3.0
    vertices, triangles = box(width, depth, height)
    parts = [("Shrinkage bar 100mm", vertices, triangles, (78.0, 123.0, 0.0))]
    return parts, {"Shrinkage bar 100mm": (width, depth, height)}


def reference_cube_parts(side=25.6):
    """A plain cube, used as a neutral reference project.

    Deliberately generated rather than copied. The original workflow used a
    cube saved out of OrcaSlicer, but only its configuration was ever read -
    the geometry was never reused. Generating eight vertices here removes any
    question about where the shape came from.
    """
    vertices, triangles = box(side, side, side)
    parts = [("Reference cube", vertices, triangles, (110.0, 110.0, 0.0))]
    return parts, {"Reference cube": (side, side, side)}


def _model_xml(parts, title, application="centauri_calibrator"):
    chunks = ['<?xml version="1.0" encoding="UTF-8"?>',
              '<model unit="millimeter" xml:lang="en-US" xmlns="%s">' % NS_CORE,
              '<metadata name="Application">%s</metadata>' % application,
              '<metadata name="Title">%s</metadata>' % title,
              '<metadata name="CreationDate">%s</metadata>'
              % datetime.date.today().isoformat(),
              '<resources>']
    for index, (name, vertices, triangles, _) in enumerate(parts, start=1):
        chunks.append('<object id="%d" type="model" name="%s">' % (index, name))
        chunks.append('<mesh><vertices>')
        for x, y, z in vertices:
            chunks.append('<vertex x="%.4f" y="%.4f" z="%.4f"/>' % (x, y, z))
        chunks.append('</vertices><triangles>')
        for a, b, c in triangles:
            chunks.append('<triangle v1="%d" v2="%d" v3="%d"/>' % (a, b, c))
        chunks.append('</triangles></mesh></object>')
    chunks.append('</resources><build>')
    for index, (_, _, _, (dx, dy, dz)) in enumerate(parts, start=1):
        # A 3x4 matrix in 3MF order: three rotation columns, then the offset.
        chunks.append('<item objectid="%d" transform="1 0 0 0 1 0 0 0 1 %s %s %s"/>'
                      % (index, dx, dy, dz))
    chunks.append('</build></model>')
    return "\n".join(chunks)


def model_settings_xml(parts):
    """model_settings.config: part names and their binding to the plate."""
    chunks = ['<?xml version="1.0" encoding="UTF-8"?>', '<config>']
    for index, (name, _, _, _) in enumerate(parts, start=1):
        chunks.append('  <object id="%d">' % index)
        chunks.append('    <metadata key="name" value="%s"/>' % name)
        chunks.append('    <metadata key="extruder" value="1"/>')
        chunks.append('  </object>')
    chunks.append('  <plate>')
    chunks.append('    <metadata key="plater_id" value="1"/>')
    chunks.append('    <metadata key="plater_name" value=""/>')
    chunks.append('    <metadata key="locked" value="false"/>')
    for index in range(1, len(parts) + 1):
        chunks.append('    <model_instance>')
        chunks.append('      <metadata key="object_id" value="%d"/>' % index)
        chunks.append('      <metadata key="instance_id" value="0"/>')
        chunks.append('    </model_instance>')
    chunks.append('  </plate>')
    chunks.append('</config>')
    return "\n".join(chunks)


def layer_gcode_xml(commands):
    """custom_gcode_per_layer.xml: a command bound to a layer height.

    The format is taken from Orca's own files. Commands are kept to one line:
    a newline inside an XML attribute is normalised to a space, and multi-line
    G-code can end up glued together.
    """
    chunks = ['<?xml version="1.0" encoding="utf-8"?>',
              '<custom_gcodes_per_layer>', '<plate>', '<plate_info id="1"/>']
    for height, gcode in commands:
        if "\n" in gcode:
            raise ValueError("a layer command must be a single line: %r" % gcode)
        chunks.append('<layer top_z="%.2f" type="4" extruder="1" color="" '
                      'extra="%s"/>' % (height, gcode))
    chunks.append('<mode value="SingleExtruder"/>')
    chunks.append('</plate>')
    chunks.append('</custom_gcodes_per_layer>')
    return "\n".join(chunks)


def write_model(path, parts, title):
    """Bare geometry: a .3mf that carries no settings at all."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", CONTENT_TYPES_MODEL)
        z.writestr("_rels/.rels", RELS)
        z.writestr("3D/3dmodel.model", _model_xml(parts, title))
    return path


def write_project(path, parts, config, title, commands=None):
    """A full Orca project: geometry plus a settings snapshot.

    ``config`` comes from the user's own OrcaSlicer installation. It is never
    shipped: those several hundred keys include the real start G-code, and a
    mistake in them means the nozzle hitting the bed.
    """
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", CONTENT_TYPES_PROJECT)
        z.writestr("_rels/.rels", RELS)
        z.writestr("3D/3dmodel.model",
                   _model_xml(parts, title, application="OrcaSlicer 2.4.2"))
        z.writestr("Metadata/project_settings.config",
                   json.dumps(config, ensure_ascii=False, indent=1))
        z.writestr("Metadata/model_settings.config", model_settings_xml(parts))
        z.writestr("Metadata/slice_info.config", SLICE_INFO)
        if commands:
            z.writestr("Metadata/custom_gcode_per_layer.xml",
                       layer_gcode_xml(commands))
    return path


def verify(path, expected):
    """Parse a finished file and check it holds exactly what was intended.

    ``expected``: {name: (width, depth, height)} in millimetres. Returns a list
    of problems; empty means good.
    """
    import xml.etree.ElementTree as ET

    problems = []
    with zipfile.ZipFile(path) as z:
        names = set(z.namelist())
        for required in ("[Content_Types].xml", "_rels/.rels", "3D/3dmodel.model"):
            if required not in names:
                problems.append("archive is missing %s" % required)
        if problems:
            return problems
        root = ET.fromstring(z.read("3D/3dmodel.model"))

    ns = {"c": NS_CORE}
    seen = {}
    for obj in root.findall(".//c:object", ns):
        name = obj.get("name")
        verts = [(float(v.get("x")), float(v.get("y")), float(v.get("z")))
                 for v in obj.findall(".//c:vertex", ns)]
        tris = obj.findall(".//c:triangle", ns)
        if not verts:
            problems.append("%s has no vertices" % name)
            continue
        size = tuple(round(max(a[i] for a in verts) - min(a[i] for a in verts), 3)
                     for i in range(3))
        seen[name] = size
        if len(tris) < 4:
            problems.append("%s has only %d triangles" % (name, len(tris)))

    for name, size in expected.items():
        if name not in seen:
            problems.append("part %r is missing" % name)
        elif tuple(round(v, 3) for v in size) != seen[name]:
            problems.append("%s is %s mm, expected %s" % (name, seen[name], size))
    return problems
