# -*- coding: utf-8 -*-
"""Calibration-model routing and compatibility guards.

OrcaSlicer's temperature, flow, pressure-advance, max-flow and retraction
parameters live in the active calibration session.  An ordinary saved 3MF keeps
the geometry but not that mode, so this module deliberately refuses to reopen
or import those five projects.  They are started live from Orca's Calibration
menu instead.

The shrinkage bar is this project's own geometry, generated by geometry.py and
shipped in templates/.  The older construction helpers remain only for API and
test compatibility; the public workflow never needs them.
"""
import glob
import os

from . import console as c
from . import geometry, orca, paths, plates


# Which plate comes from where.
FROM_WIZARD = {
    "1_temperature.3mf": ("Температурная башня", "Nozzle temperature test"),
    "2_flow.3mf": ("Тест потока (Flow rate)", "Flow rate"),
    "3_pressure_advance.3mf": ("Pressure Advance", "Pressure Advance Test"),
    "4_max_flow.3mf": ("Максимальный объёмный расход", "Max volumetric speed test"),
    "5_retraction.3mf": ("Ретракт", "Retraction test"),
}
GENERATED = {"2b_shrinkage.3mf": "Брусок усадки"}

MATERIALS = ("PLA", "PETG", "PETG-CF", "PETG-GF", "ABS", "ASA", "PA", "TPU")

# A filament preset compatible with ANY printer. Elegoo's own profiles
# ("Generic PLA @Elegoo Centauri" and friends) list their compatible printers
# by name and know nothing of user presets: on someone else's machine the plate
# would be left without a filament and Orca would substitute an arbitrary one,
# with arbitrary temperatures. The values are not changed - they are already
# laid out in the project config - only the name of the base it derives from.
NEUTRAL_FILAMENT = {
    "PLA": "Generic PLA @System",
    "PETG": "Generic PETG @System",
    "PETG-CF": "Generic PETG-CF @System",
    "PETG-GF": "Elegoo PETG-GF @System",
    "ABS": "Generic ABS @System",
    "ASA": "Generic ASA @System",
    "PA": "Generic PA @System",
    "TPU": "Generic TPU @System",
}


def local_templates_dir(create=True):
    """Where locally built plates live. Never the repository."""
    d = os.path.join(paths.data_dir(create=create), "templates")
    if create:
        os.makedirs(d, exist_ok=True)
    return d


def _usable_project(path):
    """A plate can only be personalised when it carries Orca settings."""
    if not os.path.exists(path):
        return False
    try:
        return plates.CONFIG_ENTRY in plates.read_entries(path)
    except plates.PlateError:
        return False


def resolve(material, filename):
    """Find a plate: the user's build first, the shipped one second."""
    # Orca's tower calibration parameters live only in the active wizard
    # session.  Saving and reopening an ordinary 3MF preserves the geometry,
    # but silently loses the changing temperature / PA / speed / retraction.
    # Never offer such a saved project as a runnable calibration.
    if filename in FROM_WIZARD:
        return None
    local = os.path.join(local_templates_dir(create=False), material, filename)
    if _usable_project(local):
        return local
    shipped = os.path.join(paths.templates_dir(), material, filename)
    if _usable_project(shipped):
        return shipped
    return None


def status():
    """What project-owned (non-wizard) geometry is present, per material."""
    report = {}
    for material in MATERIALS:
        have, missing = [], []
        for filename in GENERATED:
            shipped = os.path.join(paths.templates_dir(), material, filename)
            (have if os.path.exists(shipped) else missing).append(filename)
        report[material] = {"have": have, "missing": missing}
    return report


# ------------------------------------------------------------- generated

def build_shrinkage(material, reference_config=None):
    """Generate the shrinkage plate. Entirely our own geometry."""
    if not reference_config:
        raise plates.PlateError(
            "для плиты усадки нужна конфигурация из локального проекта Orca; "
            "сначала импортируй одну плиту из мастера")
    parts, expected = geometry.shrinkage_parts()
    target = os.path.join(local_templates_dir(), material, "2b_shrinkage.3mf")

    config = dict(reference_config)
    config, _ = plates.strip_personal(config)
    name = NEUTRAL_FILAMENT.get(material)
    if name:
        config["filament_settings_id"] = [name]
    geometry.write_project(target, parts, config,
                           "Калибровка: усадка (%s)" % material)

    problems = geometry.verify(target, expected)
    return target, problems


# ---------------------------------------------------------- from the wizard

def import_from_wizard(source, material, filename, reference_config=None):
    """Take a project the user saved from Orca's calibration wizard.

    It is sanitised on the way in - print_host and personal preset ids removed -
    so that even the user's own local template holds nothing that would leak if
    they later attached it to a bug report.
    """
    if filename in FROM_WIZARD:
        raise plates.PlateError(
            "сохранённый проект Orca теряет режим калибровки; "
            "запускай этот тест прямо из меню «Калибровка» во время прогона")
    if not os.path.exists(source):
        raise plates.PlateError("файл не найден: %s" % source)
    target = os.path.join(local_templates_dir(), material, filename)
    os.makedirs(os.path.dirname(target), exist_ok=True)
    removed = plates.sanitise_template(
        source, target,
        filament_settings_id=NEUTRAL_FILAMENT.get(material),
        printer_settings_id="%s %s nozzle" % (orca.SUPPORTED_PRINTER_MODEL,
                                              orca.SUPPORTED_NOZZLE))
    return target, removed


def find_saved_projects(search_dirs=None):
    """Look for .3mf files that look like saved wizard output."""
    roots = search_dirs or [
        os.path.join(os.path.expanduser("~"), "Downloads"),
        os.path.join(os.path.expanduser("~"), "Documents"),
        os.path.join(os.path.expanduser("~"), "Desktop"),
    ]
    found = []
    for root in roots:
        if not os.path.isdir(root):
            continue
        for path in glob.glob(os.path.join(root, "*.3mf")):
            found.append(path)
    return sorted(found)


# ------------------------------------------------------------------ flow

def guide(argv=None):
    c.say("%s=== Калибровочные модели ===%s" % (c.BOLD, c.RESET))
    c.say("")
    c.ok("Ничего подготавливать не нужно.")
    c.say("  Температура, поток, Pressure Advance, максимальный расход и")
    c.say("  ретракт запускаются прямо из меню «Калибровка» OrcaSlicer.")
    c.say("  Калибратор покажет точный диапазон и шаг для каждого теста.")
    c.say("  Собственная 100-мм модель усадки уже входит в комплект.")
    c.say("")
    c.dim("Почему сохранённые башни не используются: обычный 3MF хранит модель,")
    c.dim("но не активный режим мастера Orca; после повторного открытия шкала")
    c.dim("температуры/PA/скорости/ретракта пропадает.")
    c.say("")
    c.ok("Запускай Калибровать.cmd")
    c.say("Подробно: docs/templates.md")
    return 0


def _reference_config():
    """The machine configuration, read from the user's own Orca.

    The original workflow kept a saved cube project as the donor for this. That
    is not shipped here for the same licensing reason as the towers, and it does
    not need to be: the configuration can be read from the installation that is
    already on this machine.
    """
    saved = os.path.join(paths.data_dir(), "reference-project.3mf")
    if os.path.exists(saved):
        try:
            entries = plates.read_entries(saved)
            return plates.read_config(entries)
        except plates.PlateError:
            pass
    return None


def adopt_reference(source, material=None):
    """Store a project saved from the user's Orca as the configuration donor.

    Sanitised on the way in, and kept in the data directory - never in the
    repository, never published.
    """
    target = os.path.join(paths.data_dir(), "reference-project.3mf")
    removed = plates.sanitise_template(
        source, target,
        filament_settings_id=NEUTRAL_FILAMENT.get(material),
        printer_settings_id="%s %s nozzle" % (orca.SUPPORTED_PRINTER_MODEL,
                                              orca.SUPPORTED_NOZZLE))
    return target, removed


def main(argv=None):
    try:
        return guide(argv)
    except c.Cancelled:
        c.say("\nПрервано.")
        return 1
    except KeyboardInterrupt:
        c.say("\nПрервано.")
        return 1
